### ISSUE TITLE
建.fai索引的时候，将 XM_005682112.1 处理为 XM_005682112，有意漏掉版本号？

### ISSUE THREAD

**Issue by quwubin** [shenwei356/bio#2]
https://github.com/shenwei356/bio/blob/master/seqio/fai/fai.go#L110

我发现建.fai索引的时候，将 XM_005682112.1 处理为 XM_005682112，是否有意这样？

**Comment by shenwei356** [comment]
solved

**Comment by quwubin** [comment]
是索引了一半，后面因为长度不一致停了，并非描述中的问题。
