### ISSUE TITLE
GuessQualityEncoding Panic issue.

### ISSUE THREAD

**Issue by srynobio** [shenwei356/bio#3]
Hello I'm running into an issue while creating a fastq validator using your fastx package.  I've narrowed it down to my call to `GuessQualityEncoding`

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/shenwei356/bio/seq.GuessQualityEncoding(0xc4207536d0, 0x4a, 0x4a, 0xc4205e0140, 0xc4205d0fc0, 0x31)
	/Users/srynobio1/go/src/github.com/shenwei356/bio/seq/qual.go:225 +0x308
main.main()
	/Users/srynobio1/Projects/goFqValidator/goFqValidator.go:61 +0x427
exit status 2
```

https://github.com/shenwei356/bio/blob/61346d857d85f5f82121e675faf74bbfc5baf503/seq/qual.go#L225

And here's the fastq record that the error occurs:

```
@HWI-ST0831_0238:5:1109:13365:88075#CTTGTACTTGTA/2
GGGGGCAGAACGGCCGACCGCCACCACAAGACATCCTGGGGGACAGAGGCCCTGGGCACAGCCCAGTCCCCATC
+
CCFFDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDCCD
```

**Comment by shenwei356** [comment]
It should be

    for i := 0; i < NMostCommonThreshold && i < len(countSorted); i++ {

**Comment by shenwei356** [comment]
@srynobio It's fixed, please update this package:

    go get -u github.com/shenwei356/bio

Thanks for reporting this bug.

**Comment by srynobio** [comment]
No problem!
