### ISSUE TITLE
Unable to parse protein fasta file.

### ISSUE THREAD

**Issue by srynobio** [shenwei356/bio#4]
I'm guessing your original design was focused on DNA sequence.  Do you plan on supporting amino acid encoded fasta files?

```
panic: error when parsing seq: NP_000572.2 (seq: invalid Protein letter: U)

goroutine 1 [running]:
main.digestFasta(0x7ffeefbffb17, 0x2b, 0x18)
	/Users/srynobio1/go/src/github.com/srynobio/vmccl/vmccl.go:80 +0x38c
main.main()
	/Users/srynobio1/go/src/github.com/srynobio/vmccl/vmccl.go:28 +0x531

```

**Comment by shenwei356** [comment]
`U` seems a new ambiguity code? Oh, [here](http://www.dnabaser.com/articles/IUPAC%20ambiguity%20codes.html) we can see it.

[Here](https://github.com/shenwei356/bio/blob/master/seq/alphabet.go#L36) is the alphabet this package uses. I'll update it.

**Comment by shenwei356** [comment]
I see, it's selenocysteine (`U`), I also add the pyrrolysine (`O`) to the [protein alphabet](https://github.com/shenwei356/bio/blob/master/seq/alphabet.go#L391).
